/*
 * This Java source file was generated by the Gradle 'init' task.
 */
<<<<<<< HEAD:app/src/main/java/com/moviebooking/moviebooking/App.java
package com.jnanacetana.moviebooking;
=======
package com.moviebooking;
>>>>>>> 8c29845bd52e22c9e655f1e2a0acb6eddfc9e014:app/src/main/java/com/moviebooking/App.java

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
