/*
 * This Java source file was generated by the Gradle 'init' task.
 */
<<<<<<< HEAD:app/src/test/java/com/moviebooking/moviebooking/AppTest.java
package com.jnanacetana.moviebooking;
=======
package com.moviebooking;
>>>>>>> 8c29845bd52e22c9e655f1e2a0acb6eddfc9e014:app/src/test/java/com/moviebooking/AppTest.java

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
